[versions]
assertj = "3.27.6"
commonsLang = "3.20.0"
dropwizard-metrics-influxdb = "1.3.4"
gradleOci-junitJupiter = "0.8.0"
hivemq-extensionSdk = "4.40.0"
hivemq-mqttClient = "1.3.12"
jetbrains-annotations = "26.0.2-1"
junit-jupiter = "5.10.0"
logback = "1.5.25"
mockito = "5.21.0"
protobuf = "3.25.8"
testcontainers = "2.0.3"
wiremock = "3.13.2"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
commonsLang = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang" }
dropwizard-metrics-influxdb = { module = "com.izettle:dropwizard-metrics-influxdb", version.ref = "dropwizard-metrics-influxdb" }
gradleOci-junitJupiter = { module = "io.github.sgtsilvio:gradle-oci-junit-jupiter", version.ref = "gradleOci-junitJupiter" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
hivemq-mqttClient = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "hivemq-mqttClient" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
protobuf = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-hivemq = { module = "org.testcontainers:testcontainers-hivemq", version.ref = "testcontainers" }
testcontainers-junitJupiter = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }
wiremock = { module = "org.wiremock:wiremock", version.ref = "wiremock" }

[plugins]
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
hivemq-extension = { id = "com.hivemq.extension", version = "4.0.0" }
license = { id = "com.github.hierynomus.license", version = "0.16.1" }
oci = { id = "io.github.sgtsilvio.gradle.oci", version = "0.24.0" }
protobuf = { id = "com.google.protobuf", version = "0.9.6" }
